name: Linting
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.3.0
      - uses: actions/setup-node@v6
        with:
          node-version: "25"
      - run: npm ci
      - uses: pre-commit/action@v3.0.1
