name: Linting
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - uses: pre-commit/action@v3.0.1
